### ISSUE TITLE
Incompatibility with blur mod fabric

### ISSUE THREAD

**Issue by boasbakker** [Hendrix-Shen/Tweak-My-Client#4]
Minecraft crashes when using both

**Comment by tort-oise** [comment]
Link to original issue: https://github.com/Motschen/Blur/issues/19

This is practically a repost because the Blur development forum is dead as hell, and the issue seems to be on your end.
I would also like to add, as per the original issue, that Xaero's Minimap doesn't work with TweakMyClient either. You should consider fixing it, as both are pretty popular mods, making incompatibility a very bad thing.

**Comment by tort-oise** [comment]
Also, I analysed the crash report from @boasbakker on the original issue, and it seems the problem is that Blur tries to get background colours for blurring, but as TweakMyClient has disabled it, it is blatantly incompatible, and goes through an endless loop until Java makes an exception and puts an end to its misery.

**Comment by tort-oise** [comment]
But again, don't trust me, as I am not a coder. You should look through the original crash log that they posted in the issue over there, to try and find what's wrong. Thank you.
